#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#NixOS does not setup the user's D-Bus Daemon, so doing it explicitly here
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval $(dbus-launch --exit-with-session --sh-syntax)
fi
syustemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# Some x stuff
# xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xset r rate 300 50

# Need to source environment before starting fcitx5 so that it can
# read the *_IM_MODULE and XMODIFIER variables.
source ~/.config/zsh/.zshenv
kill $(pidof fcitx5) 2>/dev/null
fcitx5 -d

feh --bg-fill --no-fehbg ~/.config/wallpaper
picom -b
sxhkd &
dwmblocks &
exec dwm

