#!/usr/bin/env sh

feh --bg-scale --no-fehbg "$HOME/.config/wallpaper"
# echo "dwm.accent: $(color-picker $WALLPAPER)" > /tmp/dwm_accent
# xrdb -override -merge /tmp/dwm_accent
# rm /tmp/dwm_accent
# kill -HUP $(pidof dwm)

