version = "1.1.14"

[class]
DEFAULT = "{class}"
"(?i)firefox"    = " "
"(?i)Anki"       = " "
"(?i)blueman-manager-wrapped" = " "
"(?i)chromium"   = " "
"(?i)discord"    = "󰊴 "
"(?i)Element"    = "󰘨 "
"(?i)emacs"      = " "
"(?i)foot"       = " "
"(?i)Gimp"       = " "
"(?i)Kitty"      = " "
"(?i)libreoffice-writer" = "󰷈 "
"(?i)mpv"        = " "
"(?i)Nsxiv"      = " "
"(?i)slack"      = "󰒱 "
"(?i)spotify"    = " "
"(?i)st"         = " "
"(?i)steam"      = " "
"(?i)virtualbox" = " "
"(?i)zathura"    = " "
"(?i)mullvad vpn"= " "

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
6 = "six"
2 = "two"
4 = "four"
3 = "three"
7 = "seven"
10 = "ten"
8 = "eight"
5 = "five"
1 = "one"
0 = "zero"
9 = "nine"

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_in_class."(?i)foot"]
"(?i)nvim" = "nvim"
"(?i)neovim" = "neovim"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"" = "^$"
"[Ss]team" = "^(Friends List.*)?$"
aProgram = "^$"
"(?i)TestApp" = ""

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = ""
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "<span color='#999999'>{icon}</span>"
client_fullscreen = "[{icon}]"
client_active = "<span color='#FFFFFF'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
